[package]
name = "rusy_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
rutie = { path = "/Users/y/personal/mp/rusy" }
lazy_static = "1.4.0"
concat-idents = "1.1.5"

[lib]
crate-type = ["cdylib"]
